### PR TITLE
Bug fix for race condition and unpredictable presence of DONE packet.

### LINKED ISSUE #214: GETROUTE does not receive responses in 0.7rc
**Version of neli**
git main branch

**Describe the bug**
Creating a `GETROUTE` request via

```rust
let dstip = Ipv4Addr::new(192, 0, 2, 0);
let raw_dstip = u32::from(dstip).to_be();
let route_attr = RtattrBuilder::default()
    .rta_type(Rta::Dst)
    .rta_payload(raw_dstip)
    .build()?;

let mut route_payload = RtBuffer::new();
route_payload.push(route_attr);

let (rtnl, _) = NlRouter::connect(NlFamily::Route, None, Groups::empty())?;

let ifroutemsg = RtmsgBuilder::default()
    .rtm_family(family)
    .rtm_dst_len(32)
    .rtm_src_len(0)
    .rtm_tos(0)
    .rtm_table(RtTable::Unspec)
    .rtm_protocol(Rtprot::Unspec)
    .rtm_scope(RtScope::Universe)
    .rtm_type(Rtn::Unspec)
    .rtm_flags(RtmF::from(RTM_F_LOOKUP_TABLE))
    .rtattrs(route_payload)
    .build()?;

let recv = rtnl
    .send(Rtm::Getroute, NlmF::REQUEST, NlPayload::Payload(ifroutemsg))?;

for response in recv {
    ...
```
(edit: `dst_len` needs to be the size of the family address length)

results in no responses.
Via strace(8) the response seems to arrive in a spawned helper fork:

Main process (pid 132773):
```
sendto(3, [{nlmsg_len=36, nlmsg_type=RTM_GETROUTE, nlmsg_flags=NLM_F_REQUEST, nlmsg_seq=0, nlmsg_pid=132773}, {rtm_family=AF_INET, rtm_dst_len=0, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_UNSPEC, rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVERSE, rtm_type=RTN_UNSPEC, rtm_flags=RTM_F_LOOKUP_TABLE}, [{nla_len=8, nla_type=RTA_DST}, inet_addr("192.0.2.0")]], 36, 0, NULL, 0) = 36
futex(0x5640cf897b58, FUTEX_WAIT_BITSET_PRIVATE, 4294967295, NULL, FUTEX_BITSET_MATCH_ANY) = 0
```

Fork (pid 132774):
```
recvfrom(3, [{nlmsg_len=112, nlmsg_type=RTM_NEWROUTE, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=132773}, {rtm_family=AF_INET, rtm_dst_len=32, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_MAIN, rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVERSE, rtm_type=RTN_UNICAST, rtm_flags=RTM_F_CLONED}, [[{nla_len=8, nla_type=RTA_TABLE}, RT_TABLE_MAIN], [{nla_len=8, nla_type=RTA_DST}, inet_addr("192.0.2.0")], [{nla_len=8, nla_type=RTA_OIF}, if_nametoindex("enp5s0")], [{nla_len=8, nla_type=RTA_PREFSRC}, inet_addr("192.168.1.42")], [{nla_len=8, nla_type=RTA_GATEWAY}, inet_addr("192.168.1.200")], [{nla_len=8, nla_type=RTA_UID}, 1000], [{nla_len=36, nla_type=RTA_CACHEINFO}, {rta_clntref=2, rta_lastuse=567495, rta_expires=0, rta_error=0, rta_used=0, rta_id=0, rta_ts=0, rta_tsage=0}]]], 32768, 0, NULL, NULL) = 112
getrandom("\xdf\x1a\x9a\x20\xa1\x25\x4b\xf8\x23\xca\xcf\x26\xcf\x84\x64\xad", 16, GRND_INSECURE) = 16
futex(0x5640cf897b58, FUTEX_WAKE_PRIVATE, 1) = 1
recvfrom(3,  <unfinished ...>)          = ?
```

Maybe `nlmsg_pid` must not be set, or the payload attribute causes timing issues?

`GETADDR` works fine:

Main process (pid 132773):
```
sendto(4, [{nlmsg_len=24, nlmsg_type=RTM_GETADDR, nlmsg_flags=NLM_F_REQUEST|NLM_F_ROOT, nlmsg_seq=0, nlmsg_pid=-17449847}, {ifa_family=AF_INET, ifa_prefixlen=0, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=0}], 24, 0, NULL, 0) = 24
futex(0x5640cf897b58, FUTEX_WAIT_BITSET_PRIVATE, 4294967295, NULL, FUTEX_BITSET_MATCH_ANY) = 0
```

Fork (pid 132775):
```
recvfrom(4, [[{nlmsg_len=76, nlmsg_type=RTM_NEWADDR, nlmsg_flags=NLM_F_MULTI, nlmsg_seq=0, nlmsg_pid=-17449847}, {ifa_family=AF_INET, ifa_prefixlen=8, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_HOST, ifa_index=if_nametoindex("lo")}, [[{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("127.0.0.1")], [{nla_len=8, nla_type=IFA_LOCAL}, inet_addr("127.0.0.1")], [{nla_len=7, nla_type=IFA_LABEL}, "lo"], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1142, tstamp=1142}]]], [{nlmsg_len=88, nlmsg_type=RTM_NEWADDR, nlmsg_flags=NLM_F_MULTI, nlmsg_seq=0, nlmsg_pid=-17449847}, {ifa_family=AF_INET, ifa_prefixlen=24, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("enp5s0")}, [[{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("192.168.1.42")], [{nla_len=8, nla_type=IFA_LOCAL}, inet_addr("192.168.1.42")], [{nla_len=8, nla_type=IFA_BROADCAST}, inet_addr("192.168.1.255")], [{nla_len=11, nla_type=IFA_LABEL}, "enp5s0"], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT|IFA_F_NOPREFIXROUTE], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=774470, tstamp=774470}]]], [{nlmsg_len=88, nlmsg_type=RTM_NEWADDR, nlmsg_flags=NLM_F_MULTI, nlmsg_seq=0, nlmsg_pid=-17449847}, {ifa_family=AF_INET, ifa_prefixlen=24, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("virbr0")}, [[{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("192.168.122.1")], [{nla_len=8, nla_type=IFA_LOCAL}, inet_addr("192.168.122.1")], [{nla_len=8, nla_type=IFA_BROADCAST}, inet_addr("192.168.122.255")], [{nla_len=11, nla_type=IFA_LABEL}, "virbr0"], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1583, tstamp=1583}]]]], 32768, 0, NULL, NULL) = 252
getrandom("\x1f\x9b\xcf\x4a\x23\xee\x90\xf2\xdf\xcc\xd4\x8b\x23\x4f\x11\x2f", 16, GRND_INSECURE) = 16
futex(0x5640cf897b58, FUTEX_WAKE_PRIVATE, 1) = 1
```

### LINKED ISSUE #223: Iterating `NlRouterReceiverHandle` blocks forever
**Version of neli**
0.7.0-rc2

**Does the documentation specify that neil's behavior is correct?**
no.

**Does there appear to be a mistake in the netlink documentation based on the kernel code?**
no.

**Describe the bug**
Iterating `NlRouterReceiverHandle` hangs occasionally. It seems that the last message contains empty payload. Here are the log messages after reproducing the issue with the example code:
<details>
  <summary>Expand log messages</summary>

```
2023-09-04T13:46:48.981Z TRACE [neli::nl] Field deserialized: Payload(Buffer)                                                                                                             
2023-09-04T13:46:48.981Z DEBUG [neli::iter] Message received: Nlmsghdr { nl_len: 1724, nl_type: 35, nl_flags: NlmF(2), nl_seq: 1170, nl_pid: 149406, nl_payload: Payload(Buffer) }        
2023-09-04T13:46:48.981Z TRACE [neli::router::synchronous] Message received: Ok(Nlmsghdr { nl_len: 1724, nl_type: 35, nl_flags: NlmF(2), nl_seq: 1170, nl_pid: 149406, nl_payload: Payload
(Buffer) })                                                                                                                                                                               
2023-09-04T13:46:48.982Z TRACE [neli::utils::synchronous] Semaphore released; current count is 0, available is 3                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::utils::synchronous] Semaphore acquired; current count is 1, available is 2                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::socket::synchronous] Buffer received: [20, 0, 0, 0, 3, 0, 2, 0, 146, 4, 0, 0, 158, 71, 2, 0, 0, 0, 0, 0]                                            
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing data type Nlmsghdr                                                                                                                
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type u32                                                                                                                    
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [20, 0, 0, 0]                                                                                                        
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: 20                                                                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type u16                                                                                                                    
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [3, 0]                                                                                                               
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: 3                                                                                                                           
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type neli::consts::nl::NlmF                                                                                                 
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [2, 0]                                                                                                               
2023-09-04T13:46:48.982Z TRACE [neli::consts::nl] Deserializing data type NlmF                                                                                                            
2023-09-04T13:46:48.982Z TRACE [neli::consts::nl] Deserializing field type u16                                                                                                            
2023-09-04T13:46:48.982Z TRACE [neli::consts::nl] Buffer to be deserialized: [2, 0]                                                                                                       
2023-09-04T13:46:48.982Z TRACE [neli::consts::nl] Field deserialized: 2                                                                                                                   
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: NlmF(2)                                                                                                                     
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type u32                                                                                                                    
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [146, 4, 0, 0]                                                                                                       
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: 1170                                                                                                                        
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type u32                                                                                                                    
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [158, 71, 2, 0]                                                                                                      
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: 149406                                                                                                                      
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing field type neli::nl::NlPayload<u16, neli::types::Buffer>                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::nl] Buffer to be deserialized: [0, 0, 0, 0]                                                                                                         
2023-09-04T13:46:48.982Z TRACE [neli::nl] Deserializing data type neli::nl::NlPayload<u16, neli::types::Buffer>                                                                           
2023-09-04T13:46:48.982Z TRACE [neli::nl] Received empty payload                                                                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::nl] Padding: [0, 0, 0, 0]                                                                                                                           
2023-09-04T13:46:48.982Z TRACE [neli::nl] Field deserialized: Empty                                                                                                                       
2023-09-04T13:46:48.982Z DEBUG [neli::iter] Message received: Nlmsghdr { nl_len: 20, nl_type: 3, nl_flags: NlmF(2), nl_seq: 1170, nl_pid: 149406, nl_payload: Empty }                     
2023-09-04T13:46:48.982Z TRACE [neli::router::synchronous] Message received: Ok(Nlmsghdr { nl_len: 20, nl_type: 3, nl_flags: NlmF(2), nl_seq: 1170, nl_pid: 149406, nl_payload: Empty })  
2023-09-04T13:46:48.982Z TRACE [neli::utils::synchronous] Semaphore released; current count is 0, available is 3                                                                          
2023-09-04T13:46:48.982Z TRACE [neli::utils::synchronous] Semaphore acquired; current count is 1, available is 2
```

</details>

**To Reproduce**
The code below reproduces the issue quite quickly. 

<details>
  <summary>Expand example code</summary>

```rust
use neli::{
    consts::{
        nl::{NlmF, Nlmsg},
        socket::NlFamily,
    },
    genl::{Genlmsghdr, GenlmsghdrBuilder, NoUserHeader},
    nl::NlPayload,
    router::synchronous::{NlRouter, NlRouterReceiverHandle},
    utils::Groups,
};
use std::error::Error;

#[neli::neli_enum(serialized_type = "u8")]
pub enum Nl80211Command {
    Unspecified = 0,
    GetReg = 31,
}
impl neli::consts::genl::Cmd for Nl80211Command {}

#[neli::neli_enum(serialized_type = "u16")]
pub enum Nl80211Attribute {
    Unspecified = 0,
    RegAlpha2 = 33,
}
impl neli::consts::genl::NlAttrType for Nl80211Attribute {}

fn main() -> Result<(), Box<dyn Error>> {
    let (socket, _) = NlRouter::connect(NlFamily::Generic, None, Groups::empty()).unwrap();
    let nl_type = socket.resolve_genl_family("nl80211").unwrap();
    let nl_payload = NlPayload::Payload(
        GenlmsghdrBuilder::<Nl80211Command, Nl80211Attribute, NoUserHeader>::default()
            .cmd(Nl80211Command::GetReg)
            .version(1)
            .build()
            .unwrap(),
    );
    loop {
        println!("\n\n\n\n\n");
        let recv: NlRouterReceiverHandle<Nlmsg, Genlmsghdr<Nl80211Command, Nl80211Attribute>> =
            socket.send(nl_type, NlmF::REQUEST | NlmF::DUMP, nl_payload.clone())?;
        for msg in recv {
            let msg = msg?;
            println!("msg={:?}", msg.nl_type());
        }
    }
}
```

</details>

**Expected behavior**
Iterating `NlRouterReceiverHandle` should never get stuck and block forever.

**Additional context**
~~This seems to only happen with synchronous code. I can't reproduce the issue with async socket.~~

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #223 
Closes #214

### CODE REVIEW

**Comment by cgzones** [comment]
This indeed resolve #214; thanks!

Could you include a regression test to prevent future breakage?

**Comment by jbaublitz** [comment]
Absolutely. Is the specific operation you were running that triggered the bug sufficient to just add to a unit test or did you want something more involved?

**Comment by cgzones** [comment]
> Is the specific operation you were running that triggered the bug sufficient to just add to a unit test or did you want something more involved?

Should be sufficient, since it was 100% reproducible for me.

**Comment by jbaublitz** [comment]
I'll try to get to this early next week.

**Comment by dlon** [comment]
Thank you for fixing this! @jbaublitz could you release a new version containing the fix?

**Comment by jbaublitz** [comment]
@dlon Working on #224 tonight and will hopefully release 0.7.0-rc3 by tomorrow.

**Pull request merged**
