### PR TITLE
Migrate to tokio 0.2 (alpha) to support std::future

### PR DESCRIPTION
**Pull request by another-s347**

### CODE REVIEW

**Comment by jbaublitz** [comment]
@another-s347 I'm going to wait to review this until CI passes. Thanks for doing this!

**Comment by another-s347** [comment]
To get this CI pass, we may need to wait 1.39 stable then remove some try!...

**Comment by jbaublitz** [comment]
The instances of `try!()` have already been removed in the most recent release so you should probably rebase onto master as it is now to get CI to pass. As for the warnings about unstable APIs, I'd prefer that anyway as I'm trying to keep `neli` building on stable and as consistent as possible moving forward.

**Comment by another-s347** [comment]
I made a basic futures::Sink impl for NlSocket, but need to review. Shall I create another PR or just push it to this one?

**Comment by jbaublitz** [comment]
@another-s347 I apologize for the delay. I lost track of this PR. First, let's try getting this working with CI. I'm not opposed to a `Sink` implementation once CI is passing as it does relate to the new version of tokio. Keep me posted an don't hesitate to ping me if I lose track of this again.

**Comment by another-s347** [comment]
Currently, `proc_macro2` blocks it from building on `musl` target, but it is heavily used by `tokio(tokio-tracing)` and `pin-project`.

**Comment by another-s347** [comment]
@jbaublitz  Tokio is going to publish a new release soon, so I made one with their master branch. Once they actually push it, we may good to go

**Comment by jbaublitz** [comment]
Okay, great. Now that CI is passing, I'll start to review. One initial question: did they remove those dependencies in later versions? Is that why updating resolves this problem?

**Comment by another-s347** [comment]
For these sub-crates of `tokio` and `futures-rs` that we need, yes.

**Comment by jbaublitz** [comment]
Hi @another-s347, I am truly sorry for the delay. I'm reviewing this PR today. I'll pull it down locally and test it against all of my example programs and if those work and the code seems to be reasonably clean, I'll merge this today. Again, my apologies.

**Comment by jbaublitz** [comment]
See #75 for further activity.

**Pull request closed without merging**
