### PR TITLE
rtnl: Fix Ifinfomsg serialization

### PR DESCRIPTION
**Pull request by skrap**
* Fix serialization and deserialization of `Ifinfomsg`.  There were a few small problems.
* Switch from `AddrFamily` to `Af` enum, as it matches the size of the `ifinfomsg` field (1 byte).

### CODE REVIEW

**Comment by jbaublitz** [comment]
At first glance, this looks great! Thanks for the contribution. I'll take it from here but just wanted to give you a heads up that I'm going to modify the test slightly as I don't want the data being deserialized to assume endianness. I don't know of anyone who's used it on big endian yet but I don't want it to break on them just in case that happens. I'll merge soon.

**Comment by jbaublitz** [comment]
@skrap I'm going to try to get these tests edited as soon as possible. I apologize for the delay. Picking back up after getting set up at my new job.

**Comment by skrap** [comment]
On Thu, 2019-08-01 at 17:41 -0700, John Baublitz wrote:
> @skrap I'm going to try to get these tests edited as soon as
> possible. I apologize for the delay. Picking back up after getting
> set up at my new job.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

No worries at all!  Thanks for all your work on this, and congrats on
the new gig.

**Comment by jbaublitz** [comment]
I've reviewed this and had to remove some tests as it seemed like it was raw strace data from your machine, but other than that, I'm going to merge this as I want this working until I get the change to really review and test out rtnetlink support a little more extensively. Thanks for your contribution!

**Comment by jbaublitz** [comment]
This PR is incorporated into branch `v0.4.3-r2` for now. Will try to merge to master once I get CI working.

**Comment by jbaublitz** [comment]
Merged

**Pull request closed without merging**
