### PR TITLE
Update consts.rs for ability to autogenerate documentation for macro-defined netlink constants

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #14

### CODE REVIEW

**Comment by jbaublitz** [comment]
Hi @Dieff, let me know if you have any additional input before I merge. Thanks so much for putting the time into doing that!

**Comment by Dieff** [comment]
It's been a while since I have worked with this library, I'm hoping to do so again now though. From the perspective of a developer using it as a dependency, having additional information on the docs.rs page is a big help.

Are you happy with the new syntax for the macros? I felt it was a bit awkward having to put the comment inside the macro, instead of putting it above the definition like with most doc comments. With the current approach you write:
```
impl_var!(
  /// test doc comment
  (MyConst, u16,
    Id => 1,
    Name => 2,
  )
);
```
But I think it would be more convenient to be able to write
```
/// test doc comment
impl_var!(MyConst, u16,
    Id => 1,
    Name => 2,
);
```

 I am pretty inexperienced with the Rust macro system and couldn't work out a way to include a comment from outside the macro in the generated code (if this is even possible?), so I went with the former method.

If the way the macros work here is good enough, I don't have anything to add at the moment. I hope to use the new system to PR some new `libc` values and constants for Wireguard related Netlink the near future.

**Comment by jbaublitz** [comment]
I can say that one way around this is procedural macros. I've written them before and can make that happen if that's what you prefer? It could make this cleaner for sure but I'm also not sure it's worth the investment given that this works. It would provide more flexibility on annotating enum variants, that is definitely one benefit. I'll take a look at the macro you've provided in more depth and see if I can make it a little bit cleaner and more flexible and then report back here. Thanks again!

**Comment by jbaublitz** [comment]
I made the syntax a little cleaner and removed the unnecessary parentheses that make the syntax a bit clunkier because of the macro system in Rust. This makes it look more like the enum it generates and is probably less likely to cause headaches for beginners using this macro. Going to merge.

**Pull request merged**
