### PR TITLE
NlSocketHandle: do not expect another ack message, if only an ack message is send

### PR DESCRIPTION
**Pull request by Kloenk**
fix for #134

### CODE REVIEW

**Comment by Kloenk** [comment]
I guess the failing clippy pipeline is not from my changes.

**Comment by jbaublitz** [comment]
@Kloenk Two comments:
1. The clippy failure is indeed not your fault. Don't worry about that one.
2. I don't actually return the ACKs but do validation for them in the `NlSocketHandle`. Your change would cause the `ACK` to be returned which I don't do anywhere else. I would prefer to pass back an `Ok(None)` after the ACK validation is done.

Can you tell me a little bit more about why you want the ACK passed back?

**Comment by Kloenk** [comment]
Mostly for sequence validation. But I could also work with just Ok(None). Only error ist really annoying

**Comment by jbaublitz** [comment]
If I put up a PR, can you test it today?

**Comment by jbaublitz** [comment]
Also just a note that if you ever want to parse the ACK yourself, `recv_all()` does not processing and just passes back all of the parsed packets in a sequence.

**Comment by Kloenk** [comment]
> If I put up a PR, can you test it today? I'm looking to get the next release out today.

Yes, I can do that. Should I help somehow?

**Comment by jbaublitz** [comment]
Just give #138 a try and let me know how that works.

**Comment by Kloenk** [comment]
On it, will probably take around an hour, as I have to compile a kernel to test it (This is only because I have a unsigned regdb, and does not change the nl80211 interface)

**Comment by jbaublitz** [comment]
Not a problem! Let me know once you've verified it. Closing in favor of #138.

**Pull request closed without merging**
