### PR TITLE
Add more IPLA flags, from newer libc

### PR DESCRIPTION
**Pull request by joshtriplett**
Update the libc dependency accordingly.

### CODE REVIEW

**Comment by joshtriplett** [comment]
This is a draft, and can't be merged until libc PR https://github.com/rust-lang/libc/pull/2020 is merged and released.

**Comment by joshtriplett** [comment]
(force-pushed to re-run CI)

**Review by jbaublitz — CHANGES_REQUESTED** [review]
If you're going to add optional trailing commas, could you make that change for all of the relevant macros? I don't wanna be in a confusing, inconsistent in-between where some accept them and some don't.

**Comment by joshtriplett** [comment]
@jbaublitz Done. I've now added trailing-comma support to *all* exported macros that accept comma-separated lists.

**Review by jbaublitz — APPROVED** [review]

**Pull request merged**
